# Generated by Django 2.1.5 on 2020-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
